CREATE database BANCO_DO_BUTUCA;
USE BANCO_DO_BUTUCA;
CREATE TABLE CONTA_CORRENTE (
NUMERO INTEGER NOT NULL primary KEY,
SALDO DECIMAL (10,2) NOT NULL,
NOME VARCHAR (100) NOT NULL
);
INSERT INTO CONTA_CORRENTE VALUES
(1001,900.60,'AMELAO TROMBONNI'),
(1002,200.05,'ALCIONE TROMBONNI'),
(1003,1688.55,'ELSA SOARES TROMBONNI');
SELECT *FROM CONTA_CORRENTE;

DELIMITER //
CREATE PROCEDURE TRANSFERENCIA(
IN ORIGEM INTEGER,
IN DESTINO INTEGER,
IN VALOR DECIMAL (10,2)
)
BEGIN
DECLARE SALDO_ORIGEM DECIMAL(10,2);
DECLARE SALDO_DESTINO DECIMAL(10,2);

SELECT SALDO INTO SALDO_ORIGEM FROM CONTA_CORRENTE WHERE NUMERO = ORIGEM;
SELECT SALDO INTO SALDO_DESTINO FROM CONTA_CORRENTE WHERE NUMERO = DESTINO;
IF SALDO_ORIGEM < VALOR THEN
SELECT "SALDO INSUFICIENTE PARA TRANFERENCIA";
ELSE
SELECT "TRANFERENCIA AUTORIZADA";
UPDATE CONTA_CORRENTE SET SALDO = ( SALDO_ORIGEM - VALOR) WHERE NUMERO = ORIGEM;
SELECT " VALOR R$", VALOR, "SACADO DA CONTA ",ORIGEM;
UPDATE CONTA_CORRENTE SET SALDO = (SALDO_DESTINO+VALOR) WHERE NUMERO = DESTINO;
SELECT "VALOR R$",VALOR,"DEPOSITADO NA CONTA", DESTINO;
END IF;
END //
DELIMITER ;

SELECT * FROM CONTA_CORRENTE;
CALL TRANSFERENCIA (1001,1002,500);

-- QUESTÃO 1 - EFETUANDO SAQUE --

DELIMITER //
CREATE PROCEDURE SAQUE(
IN VALOR DECIMAL(10,2),
IN ORIGEM INTEGER
)
BEGIN
DECLARE SALDO_ORIGEM DECIMAL(10,2);

SELECT SALDO INTO SALDO_ORIGEM FROM CONTA_CORRENTE WHERE NUMERO = ORIGEM;

UPDATE CONTA_CORRENTE SET SALDO = ( SALDO_ORIGEM - VALOR) WHERE NUMERO = ORIGEM;
SELECT " VALOR R$", VALOR, "SACADO DA CONTA ",ORIGEM;

END //

DELIMITER ;

SELECT * FROM CONTA_CORRENTE;
CALL SAQUE(300,1001);

-- QUESTÃO 2 - EFETUANDO DEPOSITO --

DELIMITER //
CREATE PROCEDURE DEPOSITO(
IN VALOR DECIMAL(10,2),
IN ORIGEM INTEGER
)
BEGIN
DECLARE SALDO_ORIGEM DECIMAL(10,2);

SELECT SALDO INTO SALDO_ORIGEM FROM CONTA_CORRENTE WHERE NUMERO = ORIGEM;

UPDATE CONTA_CORRENTE SET SALDO = ( SALDO_ORIGEM + VALOR) WHERE NUMERO = ORIGEM;
SELECT " VALOR R$", VALOR, "DEPOSITADO NA CONTA ",ORIGEM;

END //

DELIMITER ;

SELECT * FROM CONTA_CORRENTE;
CALL DEPOSITO(1900,1001);

-- QUESTÃO 3 - VERIFICAR SALDO --
DELIMITER //
CREATE PROCEDURE VERIFICAR(
IN VALOR DECIMAL(10,2)
)
BEGIN
SELECT * FROM CONTA_CORRENTE WHERE SALDO > VALOR;
END //
DELIMITER ;

SELECT * FROM CONTA_CORRENTE;
CALL VERIFICAR(16000);


-- QUESTÃO 4 - ATUALIZAR O SALDO DAS CONTAS --
DELIMITER //
CREATE PROCEDURE ATUALIZAR(
IN VALOR DECIMAL(10,2)
)
BEGIN
UPDATE CONTA_CORRENTE SET SALDO = VALOR WHERE NUMERO  > 1;
END //
DELIMITER ;

CALL ATUALIZAR(30000);

SELECT * FROM  CONTA_CORRENTE;
